version: "2"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 9000:80
    environment:
      NODE_ENV: production