services:
  mongo:
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_DATABASE=resume'
      - 'MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}'
    ports:
      - 27018:27017
    container_name: mongo
    volumes:
      - ../database/data:/data/db
      - ../database/dump:/db-dump
    networks:
      - shared-network
    env_file:
      - .env
      
  resume-backend:
    build:
      context: ../backend/resume
      dockerfile: backend.Dockerfile
    ports:
      - 8080:8080
    depends_on: 
      - mongo
    links:
      - mongo
    networks:
      - shared-network
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'

  nginx-react:
    container_name: ngixreactapp
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 9000:80
    environment:
      NODE_ENV: production

networks:
  shared-network:
    driver: bridge 